# Site wide global vars - eg. {{ site.title }} can be used
title: RDS Local
subtitle: RDS
version: 1.0.0
coreSize: 26KB
url: http://localhost:8000/docs/
cssPath: http://localhost:3000/docs/css/app.css
jsPath: http://localhost:3000/docs/js/app.js

blocks:
    -
        name: Banner (Review Required)
        handle: banner
        section: header
        theme: core
    -
        name: Card Grid (Review Required)
        handle: cardgrid
        section: main
        theme: core
    -
        name: Content (Review Required)
        handle: content
        section: main
        theme: core
    -
        name: Global Nav (Review Required)
        handle: globalnav
        section: header
        theme: cms
    -
        name: Footer Brand (Review Required)
        handle: footerbrand
        section: footer
        theme: core
    -
        name: Footer Sitemap (Review Required)
        handle: footersitemap
        section: footer
        theme: fw
    -
        name: Footer Simple (Review Required)
        handle: footersimple
        section: footer
        theme: na
    -
        name: Listing (Review Required)
        handle: listing
        section: main
        theme: na
    -
        name: Masthead (Review Required)
        handle: masthead
        section: header
        theme: core
    -
        name: Search (Review Required)
        handle: search
        section: header
        theme: core
    -
        name: Text-Image (Review Required)
        handle: textimg
        section: main
        theme: fw



images: https://cu-raven.s3.amazonaws.com/assets/img/raven/
some_global_images:
    -
        filename: img1.jpg
        alt: /
    -
        filename: img2.jpg
        alt: /
    -
        filename: img3.jpg
        alt: /
sitemenu:
    -
        title: first item
        url: url
    -
        title: second item
        url: url

        submenu:
            -
                title: level 2 first
                url: url

                level3:
                    -
                        title: level 3 first
                        url: url
                    -
                        title: level 3 two
                        url: url

        submenu:
            -
                title: last item
                url: url
